haiku_b_instruction = (
    "Can you write me a haiku? A haiku is a poem that consists of three phrases composed of 17 syllables in a 5, 7, 5 pattern.",
    "Could you pen a haiku for me? A haiku is a type of poem with three lines, totaling 17 syllables, arranged in a 5, 7, 5 syllable pattern.",
    "Can you compose a haiku for me? A haiku is a three-line poem with a total of 17 syllables, following a 5, 7, 5 syllable structure.",
    "Would you be able to write a haiku? It's a poem that has three lines and 17 syllables, structured in a 5, 7, 5 syllable pattern.",
    "Can you craft a haiku for me? A haiku is a poem made up of three lines and 17 syllables, in a 5, 7, 5 syllable arrangement.",
    "Could you create a haiku? A haiku is a three-line poem, consisting of 17 syllables, following a 5, 7, 5 syllable format.",
    "Can you construct a haiku for me? A haiku is a poem that has three lines and 17 syllables, in a 5, 7, 5 syllable sequence.",
    "Would you write a haiku? A haiku is a poem with three lines, totaling 17 syllables, arranged in a 5, 7, 5 syllable pattern.",
    "Can you formulate a haiku for me? A haiku is a poem that consists of three lines and 17 syllables, in a 5, 7, 5 syllable layout.",
    "Could you draft a haiku? A haiku is a three-line poem, consisting of 17 syllables, following a 5, 7, 5 syllable scheme.",
    "Can you devise a haiku for me? A haiku is a poem that has three lines and 17 syllables, in a 5, 7, 5 syllable pattern.",
    "Can you author a haiku for me? A haiku is a poem made up of three lines and 17 syllables, in a 5, 7, 5 syllable arrangement.",
    "Could you generate a haiku? A haiku is a three-line poem, consisting of 17 syllables, following a 5, 7, 5 syllable format.",
    "Can you produce a haiku for me? A haiku is a poem that has three lines and 17 syllables, in a 5, 7, 5 syllable sequence.",
    "Would you write a haiku? A haiku is a poem with three lines, totaling 17 syllables, arranged in a 5, 7, 5 syllable pattern.",
    "Can you create a haiku for me? A haiku is a poem that consists of three lines and 17 syllables, in a 5, 7, 5 syllable layout.",
    "Could you compose a haiku? A haiku is a three-line poem, consisting of 17 syllables, following a 5, 7, 5 syllable scheme.",
    "Can you design a haiku for me? A haiku is a poem that has three lines and 17 syllables, in a 5, 7, 5 syllable pattern."
)

tanka_b_instruction = (
    "Can you write me a Tanka? A Tanka is a poem that consists of five lines composed of syllables in a 5-7-5-7-7 pattern.",
    "Could you pen a Tanka for me? It's a five-line poem with a syllable structure of 5-7-5-7-7.",
    "Can you compose a Tanka for me? This type of poem has five lines and follows a 5-7-5-7-7 syllable pattern.",
    "Would you mind writing a Tanka? It's a poem with five lines, each having syllables in a 5-7-5-7-7 sequence.",
    "Can you craft a Tanka for me? It's a five-line poem with a syllable count of 5-7-5-7-7.",
    "Could you create a Tanka? It's a poem of five lines with a syllable distribution of 5-7-5-7-7.",
    "Can you draft a Tanka for me? This poem consists of five lines with a 5-7-5-7-7 syllable arrangement.",
    "Would you be able to write a Tanka? It's a five-line poem with a 5-7-5-7-7 syllable pattern.",
    "Can you formulate a Tanka for me? It's a poem with five lines, each having syllables in a 5-7-5-7-7 order.",
    "Could you construct a Tanka? It's a five-line poem with a syllable count of 5-7-5-7-7.",
    "Can you design a Tanka for me? This poem consists of five lines with a 5-7-5-7-7 syllable structure.",
    "Would you be willing to write a Tanka? It's a poem with five lines, each having syllables in a 5-7-5-7-7 sequence.",
    "Can you produce a Tanka for me? It's a five-line poem with a syllable count of 5-7-5-7-7.",
    "Can you author a Tanka for me? This poem consists of five lines with a 5-7-5-7-7 syllable arrangement.",
    "Would you consider writing a Tanka? It's a five-line poem with a 5-7-5-7-7 syllable pattern.",
    "Can you compose a Tanka for me? This poem consists of five lines with a 5-7-5-7-7 syllable structure.",
    "Would you mind crafting a Tanka? It's a poem with five lines, each having syllables in a 5-7-5-7-7 sequence.",
    "Can you generate a Tanka for me? It's a five-line poem with a syllable count of 5-7-5-7-7.",
)

line_syllable_constrained_poem_b_instruction = (
    "Can you write me a poem? It should have {k} lines. The number of syllables for the lines in the poem should follow a {pattern} pattern.",
    "Could you compose a poem for me? It needs to have {k} lines. The syllable count for each line should adhere to a {pattern} pattern.",
    "Can you pen a poem for me? It must contain {k} lines. The syllable distribution for each line should match a {pattern} pattern.",
    "Would you be able to write a poem for me? It should consist of {k} lines. The syllable arrangement for each line should conform to a {pattern} pattern.",
    "Can you craft a poem for me? It should be {k} lines long. The syllable sequence for each line should follow a {pattern} pattern.",
    "Could you create a poem for me? It should include {k} lines. The syllable structure for each line should align with a {pattern} pattern.",
    "Can you draft a poem for me? It should be composed of {k} lines. The syllable count for each line should fit a {pattern} pattern.",
    "Would you mind writing a poem for me? It should have {k} lines. The syllable count for each line should correspond to a {pattern} pattern.",
    "Can you formulate a poem for me? It should encompass {k} lines. The syllable count for each line should coincide with a {pattern} pattern.",
    "Could you devise a poem for me? It should contain {k} lines. The syllable count for each line should comply with a {pattern} pattern.",
    "Can you construct a poem for me? It should comprise {k} lines. The syllable count for each line should accord with a {pattern} pattern.",
    "Would you be willing to write a poem for me? It should have {k} lines. The syllable count for each line should be in a {pattern} pattern.",
    "Can you author a poem for me? It should include {k} lines. The syllable count for each line should be consistent with a {pattern} pattern.",
    "Could you generate a poem for me? It should consist of {k} lines. The syllable count for each line should be in accordance with a {pattern} pattern.",
    "Can you produce a poem for me? It should be made up of {k} lines. The syllable count for each line should follow a {pattern} pattern.",
    "Would you consider writing a poem for me? It should have {k} lines. The syllable count for each line should match a {pattern} pattern.",
    "Can you create a poem for me? It should be structured with {k} lines. The syllable count for each line should follow a {pattern} pattern.",
    "Could you put together a poem for me? It should have {k} lines. The syllable count for each line should adhere to a {pattern} pattern.",
    "Can you compose a poem for me? It should be arranged in {k} lines. The syllable count for each line should follow a {pattern} pattern.",
    "Would you draft a poem for me? It should be organized into {k} lines. The syllable count for each line should correspond to a {pattern} pattern.",
    "Can you write a poem for me? It should be divided into {k} lines. The syllable count for each line should align with a {pattern} pattern."    ,
)

syllable_constrained_poem_b_instruction = (
    "Can you produce a short poem where each line has {syllable} syllables?",
    "Could you create a short poem where each verse contains {syllable} syllables?",
    "Can you compose a short poem with each line having {syllable} syllables?",
    "Are you able to generate a short poem where each line consists of {syllable} syllables?",
    "Can you construct a short poem in which each line has {syllable} syllables?",
    "Could you devise a short poem where every line contains {syllable} syllables?",
    "Could you produce a short poem where each line carries {syllable} syllables?",
    "Can you craft a short poem where each line is composed of {syllable} syllables?",
    "Are you able to write a short poem where each line holds {syllable} syllables?",
    "Can you design a short poem where each line includes {syllable} syllables?",
    "Could you generate a short poem where each line is filled with {syllable} syllables?",
    "Are you capable of producing a short poem where each line carries {syllable} syllables?",
    "Can you create a short poem where each line is structured with {syllable} syllables?",
    "Could you write a short poem where each line contains {syllable} syllables?",
    "Can you compose a short poem where each line is formed with {syllable} syllables?",
    "Are you able to construct a short poem where each line is arranged with {syllable} syllables?",
    "Can you devise a short poem where each line is composed with {syllable} syllables?",
)

r_feedback_neg = (
    "The generated {form_name} is incorrect.",
    "The produced {form_name} is not correct.",
    "The created {form_name} is wrong.",
    "The {form_name} that was generated is incorrect.",
    "The {form_name} that has been generated is not correct.",
    "The {form_name} generated is erroneous.",
    "The {form_name} that's been generated is wrong.",
    "The {form_name} that was produced is incorrect.",
    "The {form_name} that has been produced is not correct.",
    "The {form_name} produced is erroneous.",
    "The {form_name} that's been produced is wrong.",
    "The {form_name} that was written is incorrect.",
    "The {form_name} that has been written is not correct.",
    "The {form_name} written is erroneous.",
    "The {form_name} that's been created is wrong.",
    "The {form_name} generated is not right.",
    "The {form_name} produced is not right.",
    "The {form_name} written is not right.",
    "The {form_name} that was generated is not right.",
    "The {form_name} that has been generated is not right.",
    "The {form_name} that's been generated is not right.",
)

r_feedback_pos = (
    "Congrats! You have successfully produced a poem that matches the assignment description.",
    "Well done! You've successfully created a poem that fits the assignment description.",
    "Bravo! You've successfully crafted a poem that aligns with the assignment description.",
    "Kudos! You've successfully composed a poem that meets the assignment description.",
    "Good job! You've successfully written a poem that corresponds to the assignment description.",
    "Excellent! You've successfully penned a poem that adheres to the assignment description.",
    "Great work! You've successfully generated a poem that matches the assignment description.",
    "Nice work! You've successfully constructed a poem that fits the assignment description.",
    "Superb! You've successfully created a poem that is in line with the assignment description.",
    "Fantastic! You've successfully produced a poem that complies with the assignment description.",
    "Splendid! You've successfully written a poem that fits the assignment description.",
    "Remarkable! You've successfully made a poem that aligns with the assignment description.",
    "Terrific! You've successfully composed a poem that corresponds to the assignment description.",
    "Outstanding! You've successfully written a poem that adheres to the assignment description.",
    "Wonderful! You've successfully generated a poem that matches the assignment description.",
    "Amazing! You've successfully constructed a poem that fits the assignment description.",
    "Incredible! You've successfully created a poem that is in line with the assignment description.",
    "Marvelous! You've successfully produced a poem that complies with the assignment description.",
)

hn_feedback = (
    "This is because the {form_name} needs to have exactly {k} lines.",
    "The reason is that the {form_name} must contain exactly {k} lines.",
    "This is due to the {form_name} requiring exactly {k} lines.",
    "The {form_name} is required to have precisely {k} lines, hence this.",
    "This is because the {form_name} is expected to have exactly {k} lines.",
    "The {form_name} should have exactly {k} lines, that's why.",
    "This is because the {form_name} is supposed to contain exactly {k} lines.",
    "The {form_name} needs to consist of exactly {k} lines, that's the reason.",
    "This is because the {form_name} is required to consist of exactly {k} lines.",
    "The {form_name} is expected to consist of exactly {k} lines, hence this.",
    "This is due to the {form_name} being required to have exactly {k} lines.",
    "The {form_name} must have exactly {k} lines, that's the reason.",
    "This is because the {form_name} should contain exactly {k} lines.",
    "The {form_name} is supposed to have exactly {k} lines, hence this.",
    "This is because the {form_name} needs to be made up of exactly {k} lines.",
    "The {form_name} is required to be made up of exactly {k} lines, that's why.",
    "This is due to the {form_name} needing to contain exactly {k} lines.",
    "The {form_name} should be made up of exactly {k} lines, hence this.",
    "This is because the {form_name} is expected to be made up of exactly {k} lines.",
    "The {form_name} is supposed to consist of exactly {k} lines, that's the reason.",
    "This is due to the {form_name} expected to have exactly {k} lines."
)

fp_feedback = (
    "You wrote {observed_num} lines. Write {improv_direction} lines.",
    "You've penned {observed_num} lines. Compose {improv_direction} lines.",
    "You've authored {observed_num} lines. Create {improv_direction} lines.",
    "You've generated {observed_num} lines. Construct {improv_direction} lines.",
    "You've created {observed_num} lines. Pen {improv_direction} lines.",
    "You've developed {observed_num} lines. Produce {improv_direction} lines.",
    "You've constructed {observed_num} lines. Generate {improv_direction} lines.",
    "You've written down {observed_num} lines. Jot down {improv_direction} lines.",
    "You've jotted down {observed_num} lines. Write down {improv_direction} lines.",
    "You've drafted {observed_num} lines. Write out {improv_direction} lines.",
)

line_fp_feedback_1 = (
    "Here are some suggestions to fix your error:",
    "Here are a few recommendations to rectify your mistake:",
    "Here are some proposals to correct your error:",
    "Here are some ideas to resolve your issue:",
    "Here are some tips to fix your error:",
    "Here are some advice to repair your mistake:",
    "Here are some solutions to fix your problem:",
    "Here are some hints to correct your error:",
    "Here are some pointers to rectify your mistake:",
    "Here are some suggestions to mend your error:",
    "Here are some guidelines to resolve your issue:",
    "Here are some strategies to fix your error:",
    "Here are some methods to correct your mistake:",
    "Here are some steps to resolve your problem:",
    "Here are some instructions to amend your error:",
    "Here are some directions to repair your mistake:",
    "Here are some approaches to fix your problem:",
    "Here are some tactics to correct your error:",
    "Here are some procedures to rectify your mistake:",
    "Here are some measures to resolve your issue:",
    "Here are some ways to amend your error:",
)

line_fp_feedback_2 = (
    'The line: "{line}" has {count} syllables. It should only have {k} syllables. You should rewrite the line to have {improv_direction} syllables.',
    'The sentence: "{line}" contains {count} syllables. Ideally, it should only contain {k} syllables. Please modify the sentence to include {improv_direction} syllables.',
    'The phrase: "{line}" has {count} syllables. It is supposed to have only {k} syllables. You need to revise the phrase to have {improv_direction} syllables.',
    'The text: "{line}" includes {count} syllables. It should only include {k} syllables. You should edit the text to include {improv_direction} syllables.',
    'The writing: "{line}" includes {count} syllables. It should only include {k} syllables. You should edit the text to include {improv_direction} syllables.',
    'The verse: "{line}" has {count} syllables. It should have {k} syllables only. You should rephrase the verse to have {improv_direction} syllables.',
    'The expression: "{line}" holds {count} syllables. It should hold only {k} syllables. You should restructure the expression to hold {improv_direction} syllables.',
    'The utterance: "{line}" possesses {count} syllables. It should possess only {k} syllables. You should redraft the utterance to possess {improv_direction} syllables.',
)
